<?php if ( ! defined( 'ABSPATH' ) ) { exit; } ?><!doctype html>
<html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo( 'charset' ); ?>"><meta name="viewport" content="width=device-width, initial-scale=1"><?php wp_head(); ?></head><body <?php body_class(); ?>><?php wp_body_open(); ?>
<a class="skip-link" href="#primary"><?php esc_html_e( 'Skip to content', 'illuminated-path' ); ?></a>
<?php if ( get_theme_mod( 'ip_promo_enabled', false ) ) : $promo_url = get_theme_mod( 'ip_promo_url', '' ); $promo_code = trim( (string) get_theme_mod( 'ip_promo_code', '' ) ); ?>
<div class="ip-promo-bar"><?php if ( $promo_url ) : ?><a href="<?php echo esc_url( $promo_url ); ?>"><?php endif; ?><span><?php echo esc_html( get_theme_mod( 'ip_promo_text', '' ) ); ?></span><?php if ( $promo_code ) : ?><strong data-coupon-code="<?php echo esc_attr( $promo_code ); ?>"><?php echo esc_html( $promo_code ); ?></strong><?php endif; ?><?php if ( $promo_url ) : ?></a><?php endif; ?></div>
<?php endif; ?>
<header class="site-header" data-header><div class="container nav-wrap">
<a class="brand" href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home"><span class="brand-mark" aria-hidden="true"><span>✦</span></span><span class="brand-text"><strong><?php bloginfo( 'name' ); ?></strong><?php if ( get_theme_mod( 'ip_brand_suffix' ) ) : ?><small><?php echo esc_html( get_theme_mod( 'ip_brand_suffix' ) ); ?></small><?php endif; ?></span></a>
<button class="mobile-toggle" type="button" aria-expanded="false" aria-controls="primary-navigation" data-menu-toggle><span></span><span></span><span></span><span class="screen-reader-text"><?php esc_html_e( 'Menu', 'illuminated-path' ); ?></span></button>
<nav class="main-nav" id="primary-navigation" aria-label="<?php esc_attr_e( 'Primary navigation', 'illuminated-path' ); ?>" data-menu><?php if ( has_nav_menu( 'primary' ) ) { wp_nav_menu( array( 'theme_location' => 'primary', 'container' => false, 'items_wrap' => '%3$s', 'fallback_cb' => false, 'depth' => 2 ) ); } else { echo '<a href="' . esc_url( ip_shop_url() ) . '">' . esc_html( ip_text( 'shop' ) ) . '</a><a href="' . esc_url( ip_product_category_url( 'stories-of-the-prophets' ) ) . '">' . esc_html__( 'Prophet Stories', 'illuminated-path' ) . '</a><a href="' . esc_url( ip_product_category_url( 'quran-stories' ) ) . '">' . esc_html__( 'Quran Stories', 'illuminated-path' ) . '</a><a href="' . esc_url( get_permalink( get_option( 'page_for_posts' ) ) ?: home_url( '/blog/' ) ) . '">' . esc_html( ip_text( 'blog' ) ) . '</a>'; } ?></nav>
<div class="nav-actions"><?php ip_language_switcher(); ?><button class="icon-link search-toggle" type="button" aria-label="<?php esc_attr_e( 'Search books', 'illuminated-path' ); ?>" data-search-toggle>⌕</button><?php if ( class_exists( 'WooCommerce' ) ) : ?><a class="icon-link account-link" href="<?php echo esc_url( wc_get_page_permalink( 'myaccount' ) ); ?>" aria-label="<?php echo esc_attr( ip_text( 'account' ) ); ?>">♙</a><a class="icon-link cart-link" href="<?php echo esc_url( wc_get_cart_url() ); ?>" aria-label="<?php esc_attr_e( 'Shopping cart', 'illuminated-path' ); ?>"><span aria-hidden="true">🛒</span><span class="ip-cart-count"><?php echo esc_html( (string) ip_cart_count() ); ?></span></a><?php endif; ?><a class="btn btn-primary nav-shop" href="<?php echo esc_url( ip_shop_url() ); ?>"><?php echo esc_html( ip_text( 'shop' ) ); ?></a></div>
</div><div class="header-search-panel" data-search-panel hidden><div class="container"><?php if ( shortcode_exists( 'ip_book_search' ) ) { echo do_shortcode( '[ip_book_search]' ); } else { get_search_form(); } ?></div></div></header>
